CREATE DATABASE PHPClassWinter2017 DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
USE PHPClassWinter2017;

CREATE TABLE IF NOT EXISTS test (
	id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
        dataone VARCHAR(150) DEFAULT NULL,
	datatwo VARCHAR(150) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1;